### ISSUE TITLE
How am I supposed to install it?

### ISSUE THREAD

**Issue by pablobcb** [virgo-agent-toolkit/luvit-bourbon#15]
lit? npm? download it and ...?

thank you!

**Comment by rphillips** [comment]
i haven't updated this to the new version of luvit using lit... it will happen

**Comment by pablobcb** [comment]
so its impossible to use it right now?

**Comment by rphillips** [comment]
this will work with luvit:master. We have been using the tap module within luvit's luvi-up branch.

**Comment by rphillips** [comment]
fixed it up... you can use `virgo-agent-toolkit/bourbon@0.2.1` with the luvi-up branch of luvit.

**Comment by pablobcb** [comment]
Thank you for the fast response :)

**Comment by rphillips** [comment]
welcome!
